arch:
  - amd64
  - ppc64le
language: python
cache: pip
dist: bionic
python:
    - '2.7'
    - '3.5'
    - '3.6'
    - '3.7'
    - '3.8'
    - pypy2
    - pypy3
matrix:
   exclude:
      - python: pypy2
        arch: ppc64le
      - python: pypy3
        arch: ppc64le
install:
    - pip install codecov tox
script:
    - tox -e py
after_success:
    - codecov
